services:
  - type: web
    name: reneer-dotnet-app
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    region: oregon
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: APP_DLL
        value: REENEER.dll
