services:
  - type: web
    name: reneer-dotnet-app
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    region: oregon
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      # Si quieres fijar el nombre del dll, a√±ade:
      # - key: APP_DLL
      #   value: MyProject.dll
